// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmypnhceuaqgvwxruymc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFteXBuaGNldWFxZ3Z3eHJ1eW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzYxMzMsImV4cCI6MjA2OTU1MjEzM30.u1RUqoBCszJ1TQ-m8h0ySPkvbGHu1DoXe2odIaq_pt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});